### ISSUE TITLE
keep-items.item.* Not working with GroupManager

### ISSUE THREAD

**Issue by SolarXD** [robinjam/keep-items#10] opened 2014-01-20 14:58 UTC
Unless I explicitly put in keep-items.item.<itemid> it will not keep items if a users is given keep-items.item.*

I've checked with the Essentials team that manages GroupManager and they've stated the issue is with keepitems.

<SkyBirdSoar>: "use keep-items.items.*" -> code does not check for that permission ._.
<SkyBirdSoar>: checks everything in a loop

**Comment by robinjam** [comment] 2014-01-20 22:37
Thanks for the report, but I think the cause of this is an incompatibility with Minecraft 1.7 rather than an incompatibility with GroupManager. I've sent you a PM on BukkitDev with some more information.

Closing as duplicate of #11.

**Closed as completed by robinjam** 2014-01-20 22:37 UTC
Labels: duplicate
